apiVersion: v1
kind: Pod
metadata:
  labels:
    test: liveness
  name: liveness-exec
spec:
  containers:
  - name: liveness
    image: cupy/nvidia-cuda:10.2-runtime-ubuntu18.04
    args:
    - /bin/sh
    - -c
    - sleep infinity
